FROM node:22-bookworm

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npx playwright install --with-deps chromium

COPY . .

RUN npm run build

EXPOSE 3000
EXPOSE 8788

CMD ["npm","start"]